/**
 * Error Codes
 * Standardized error codes for API responses
 */

export const ERROR_CODES = {
  // Authentication & Authorization
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_USER_INACTIVE: 'AUTH_USER_INACTIVE',
  AUTH_PASSWORD_WEAK: 'AUTH_PASSWORD_WEAK',

  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_EMAIL_TAKEN: 'USER_EMAIL_TAKEN',
  USER_USERNAME_TAKEN: 'USER_USERNAME_TAKEN',
  USER_UPDATE_FAILED: 'USER_UPDATE_FAILED',

  // Category
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_ALREADY_EXISTS: 'CATEGORY_ALREADY_EXISTS',
  CATEGORY_INVALID: 'CATEGORY_INVALID',

  // Quiz
  QUIZ_NOT_FOUND: 'QUIZ_NOT_FOUND',
  QUIZ_NOT_ACTIVE: 'QUIZ_NOT_ACTIVE',
  QUIZ_MAX_ATTEMPTS_REACHED: 'QUIZ_MAX_ATTEMPTS_REACHED',
  QUIZ_INVALID: 'QUIZ_INVALID',
  QUIZ_INVALID_DURATION: 'QUIZ_INVALID_DURATION',
  QUIZ_QUESTIONS_MISSING: 'QUIZ_QUESTIONS_MISSING',

  // Questions
  QUESTION_NOT_FOUND: 'QUESTION_NOT_FOUND',
  QUESTION_INVALID_TYPE: 'QUESTION_INVALID_TYPE',
  QUESTION_INVALID: 'QUESTION_INVALID',

  // Attempt
  ATTEMPT_NOT_FOUND: 'ATTEMPT_NOT_FOUND',
  ATTEMPT_NOT_IN_PROGRESS: 'ATTEMPT_NOT_IN_PROGRESS',
  ATTEMPT_TIME_EXPIRED: 'ATTEMPT_TIME_EXPIRED',
  ATTEMPT_INVALID_ANSWER: 'ATTEMPT_INVALID_ANSWER',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',

  // Database
  DATABASE_ERROR: 'DATABASE_ERROR',
  DATABASE_CONNECTION_ERROR: 'DATABASE_CONNECTION_ERROR',

  // Server
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  // Rate Limiting
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Not Found
  NOT_FOUND: 'NOT_FOUND',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',

  // Conflict
  CONFLICT: 'CONFLICT',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
